name: photoz
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - astropy==4.1
  - hyperas
  - joblib
  - jupyter
  - lightgbm
  - matplotlib
  - numpy
  - pip
  - scipy
  - setuptools
  - tensorflow
  - xgboost
  - pip:
    - hyperopt
    - pandas
    - scikit-learn
    - seaborn
    - sklearn
    - tqdm
    - vos
